-- Part 1
-- (1)
SELECT COUNT(St_Age)
FROM STUDENT
-- (2)
SELECT T.TOP_NAME , COUNT(C.Crs_Id)
FROM TOPIC T INNER JOIN COURSE C
ON T.TOP_ID = C.TOP_ID 
GROUP BY T.TOP_NAME
-- (3)
SELECT S.St_Fname , M.*
FROM STUDENT S , STUDENT M
WHERE S.St_super = M.St_Id
-- (4)
SELECT ISNULL(S.St_Id,'0000') AS StudentID, 
ISNULL(CONCAT(S.St_Fname,' ',S.St_Lname),'Name not found') AS FullName ,
ISNULL(D.Dept_Name,'First name not found') AS DepartmentName
FROM Student S , Department D
WHERE S.Dept_Id = D.Dept_Id
-- (5)
SELECT Ins_Name , ISNULL(Salary,'0000')
FROM INSTRUCTOR 
-- (6)
SELECT M.St_Fname , COUNT(S.St_Id) AS STUNDENT_CONT
FROM STUDENT S , STUDENT M
WHERE S.St_super = M.St_Id
GROUP BY M.St_Fname
-- (7)
SELECT MAX(Salary) AS INS_MAX_SALARY , MIN(Salary) AS INS_MIN_SALARY
FROM INSTRUCTOR
-- (8)
SELECT AVG(SALARY) AS AVG_SALARY
FROM INSTRUCTOR

-- Part 2
-- DQL
-- (1)
SELECT P.Pname , SUM(W.[Hours])
FROM PROJECT P INNER JOIN WORKS_FOR W 
ON P.Pnumber = W.PNO INNER JOIN Employee E 
ON E.SSN = W.ESSN
GROUP BY P.Pname
-- (2)
SELECT D.DNAME , MAX(E.Salary) AS MAX , MIN(E.Salary) AS MIN , AVG(E.Salary) AS AVG
FROM DEPARTMENTS D , EMPLOYEE E 
WHERE D.DNUM = E.Dno
GROUP BY D.DNAME 
-- (3)
SELECT D.DNAME , E.Fname , E.Lname, P.Pname
FROM EMPLOYEE E INNER JOIN WORKS_FOR W 
ON E.SSN = W.ESSN  INNER JOIN Project P 
ON P.Pnumber = W.Pno INNER JOIN DEPARTMENTS D
ON D.DNUM = E.DNO
ORDER BY D.DNAME , E.Lname , E.Fname
-- (4)
UPDATE E
SET E.SALARY = E.Salary * 1.30 
FROM EMPLOYEE E INNER JOIN WORKS_FOR W 
ON E.SSN = W.ESSN  INNER JOIN Project P 
ON P.Pnumber = W.Pno
WHERE P.PNAME = 'Al Rabwah' 
-- DML
-- (1)
INSERT INTO Departments 
VALUES ('DEPT IT',100,112233,'1-11-2006')
-- (2)
-- (a)
UPDATE Employee
SET DNO = 100 
WHERE SSN = 968574 

UPDATE DEPARTMENTS
SET MGRSSN = 968574
WHERE DNUM = 100
-- (b)
INSERT INTO Employee (Fname,Lname,SSN,DNO)
VALUES ('Omar','Khalid',102672,20)

UPDATE DEPARTMENTS
SET MGRSSN = 102672
WHERE DNUM = 20
-- (c)
UPDATE Employee
SET Superssn = 102672 
WHERE SSN = 102660 

-- (3)
UPDATE DEPARTMENTS SET MGRSSN = NULL WHERE MGRSSN = 223344
DELETE Dependent WHERE ESSN = 223344
UPDATE EMPLOYEE SET SUPERSSN = NULL WHERE SUPERSSN = 223344
DELETE FROM WORKS_FOR WHERE ESSN = 223344
DELETE EMPLOYEE WHERE SSN = 223344

-- Part(3)
-- (1)
SELECT E.Fname, E.Lname
FROM Employee AS E
INNER JOIN Works_for AS W ON E.SSN = W.ESSN
INNER JOIN Project AS P ON W.Pno = P.Pnumber
WHERE E.Dno = 10 AND P.Pname = 'AL Rabwah' AND W.Hours >= 10
-- (2)
SELECT E.Fname, E.Lname
FROM Employee AS E
WHERE E.SuperSSN = 223344
-- (3)
SELECT E.*
FROM Employee  E , DEPARTMENTS M
WHERE E.SSN = M.MGRSSN
-- (4)
SELECT E.Fname, E.Lname, P.Pname
FROM Employee E INNER JOIN Works_for W 
ON E.SSN = W.ESSN INNER JOIN Project P 
ON W.Pno = P.Pnumber
ORDER BY P.Pname
-- (5)
SELECT P.Pnumber, D.Dname, E.Lname, E.Address, E.Bdate
FROM Project P INNER JOIN Departments D 
ON P.Dnum = D.Dnum INNER JOIN Employee E 
ON D.MGRSSN = E.SSN
WHERE P.City = 'Cairo'
-- (6)
SELECT E.*, DEP.*
FROM Employee E LEFT JOIN Dependent DEP 
ON E.SSN = DEP.ESSN